### ISSUE TITLE
Filled triangle extends off top of display.

### ISSUE THREAD

**Issue by HerbOtto** [peter-l5/framebuf2#1] opened 2023-05-03 15:17 UTC
I may have found a possible bug.  In code below, the upward facing triangle [filled] would extend past its specified coordinates to off the top of the screen. 

`w = 240 // 2`
 `h = 240 // 2`
`r = 50`
`x = w`
`y = h`
`fill(BLUE)`
`triangle(x,y, x-r,y-r, x+r,y-r, RED,    True)    # UP - filled [ERROR]`
`triangle(x,y, x-r,y-r, x+r,y-r, WHITE)           # UP - no fill - OK`
`triangle(x,y, x-r,y+r, x+r,y+r, YELLOW, True)    # DOWN  - OK`
`triangle(x,y, x+r,y-r, x+r,y+r, PURPLE, True)    # RIGHT - OK`
`triangle(x,y, x-r,y-r, x-r,y+r, GREEN,  True)    # LEFT  - OK`
`show()`

Tested with Waveshare 1.3 inch LCD Display for Raspberry Pi Pico, IPS Screen Display Module, 65K RGB Colors, 240x240 Pixels, Embedded ST7789 Driver Chip, Using SPI Bus.

**Comment by peter-l5** [comment] 2023-05-03 20:16
Hi HerbOtto,
thank you for raising this issue. 
I agree that there does seem to be a bug here that occurs when the second and third y values are equal and smaller than the first.  
I have been able to reproduce it on a SH1107 128x128 OLED with the following code, and will investigate the cause. Hopefully fixing it may be as simple as replacing a `<` with `<=` but we will see. 
```
#   ...
    display.fill(0)
    display.triangle(64, 64, 40, 40, 90, 40, c=1, f=False)  # OK
    display.show()
    time.sleep(2)
    display.fill(0)
    display.triangle(64, 64, 40, 40, 90, 40, c=1, f=True)  # error
    display.show()
    time.sleep(2)
    display.fill(0)
    display.triangle(64, 64, 40, 40, 90, 41, c=1, f=True)  # OK
    display.show()
#   ...
```

**Comment by peter-l5** [comment] 2023-05-04 07:16
Hi again,  

I have found that changing the line
 ```y = 0``` 
in the triangle method to
 ```y = y0``` 
should fix this bug. 

However, while investigating this, I also noticed that the method sometimes draws filled triangles slightly incorrectly where all three vertices have different y values. (The code seems to draw an unnecessary additional horizontal line around the middle vertex when it starts to draw the lower part of the triangle.) Once I have some repaired code I will post it up (in the coming days).

**Comment by HerbOtto** [comment] 2023-05-04 10:59
Sounds great - thanks!Sent from my iPadOn May 4, 2023, at 3:16 AM, peter-l5 ***@***.***> wrote:﻿
Hi again,
I have found that changing the line y = 0 in the triangle method to y = y0 should fix this bug. However while investigating this I found that the method sometimes draws filled triangles slightly incorrectly where all three vertices have different y values (The code seems to draw an unnecessary additional horizontal line around the middle vertex when it starts to draw the lower part of the triangle.) Once I have some repaired code I will post it up (in the coming days).

**Comment by peter-l5** [comment] 2023-05-05 00:28
The main branch is now updated with a fix for this issue. 
Any feedback on it would be welcome. 
I'll close the issue in a few days if no snags found.

**Closed as completed** 2023-05-22 20:27 UTC
